name: Update members

on:

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codingpot/github-org-member-manage-action@v1.0.0
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          mode: write
          members_filepath: members.yaml
